"""Public P0, N1 and additive N2/N3 contract model API.

Imports remain available from :mod:`latency_fingerprinting.models` even though
the implementation is organized into focused modules.
"""

from .common import (
    CONTRACT_VERSION,
    FINGERPRINT_SCHEMA_VERSION,
    MATCH_RESULT_SCHEMA_VERSION,
    OBSERVATION_SCHEMA_VERSION,
    ContractModel,
    FiniteFloat,
    MatchDecision,
    NonEmptyStr,
    NonNegativeFiniteFloat,
    NonNegativeInt,
    OutcomeResult,
    PositiveFiniteFloat,
    PositiveInt,
    ProbeApplicationMethod,
    ProbeExecutionStatus,
    ProvenanceKind,
    RestorationStatus,
    UnitInterval,
    UnknownReason,
    ValidationStatus,
    WindowPhase,
)

__all__ = [
    "CONTRACT_VERSION",
    "OBSERVATION_SCHEMA_VERSION",
    "FINGERPRINT_SCHEMA_VERSION",
    "MATCH_RESULT_SCHEMA_VERSION",
    "NonEmptyStr",
    "FiniteFloat",
    "NonNegativeFiniteFloat",
    "PositiveFiniteFloat",
    "NonNegativeInt",
    "PositiveInt",
    "UnitInterval",
    "ContractModel",
    "WindowPhase",
    "ProvenanceKind",
    "ProbeApplicationMethod",
    "ProbeExecutionStatus",
    "RestorationStatus",
    "ValidationStatus",
    "MatchDecision",
    "UnknownReason",
    "OutcomeResult",
    "ContextKey",
    "TimeBounds",
    "MetricAggregate",
    "ValidityState",
    "SourceArtifact",
    "ObservationWindow",
    "Probe",
    "FeatureDelta",
    "ResponseDelta",
    "NormalizedFeature",
    "NormalizedResponse",
    "ObservationRecord",
    "CompatibilityKey",
    "Fingerprint",
    "RankedCandidate",
    "FeatureEvidence",
    "CompatibilityResult",
    "MatchThresholds",
    "MatchResult",
    "ValidatedOutcome",
    "METRIC_REGISTRY_SCHEMA_VERSION",
    "AggregationKind",
    "ClockBasis",
    "CounterResetPolicy",
    "MetricDefinition",
    "MetricKind",
    "MetricRegistry",
    "MetricSource",
    "MetricUnit",
    "MissingDataPolicy",
    "MeasurementSample",
    "MetricSeriesStatus",
    "MetricSeriesSummary",
    "CounterInterval",
]
from .analytical_response_v2 import (
    ANALYTICAL_RESPONSE_V2_SCHEMA_VERSION,
    AnalyticalResponseV2,
    FeatureResponseV2,
    WindowFeatureEvidenceV2,
)
from .context import (
    ContextKey,
    MetricAggregate,
    ObservationWindow,
    SourceArtifact,
    TimeBounds,
    ValidityState,
)
from .feature_policy import (
    FEATURE_POLICY_SCHEMA_VERSION,
    AnalyticalDecisionPolicyV1,
    FeaturePolicyParameterV1,
    FeaturePolicyV1,
)
from .fingerprint import CompatibilityKey, Fingerprint
from .fingerprint_v2 import FINGERPRINT_V2_SCHEMA_VERSION, FingerprintV2
from .match import (
    CompatibilityResult,
    FeatureEvidence,
    MatchResult,
    MatchThresholds,
    RankedCandidate,
    ValidatedOutcome,
)
from .match_v2 import (
    MATCH_RESULT_V2_SCHEMA_VERSION,
    AnalyticalFeatureEvidenceV2,
    CandidateComparisonV2,
    MatchResultV2,
    RankedCandidateV2,
    RepositoryReferenceV2,
)
from .measurement import (
    METRIC_REGISTRY_SCHEMA_VERSION,
    AggregationKind,
    ClockBasis,
    CounterInterval,
    CounterResetPolicy,
    MeasurementSample,
    MetricDefinition,
    MetricKind,
    MetricRegistry,
    MetricSeriesStatus,
    MetricSeriesSummary,
    MetricSource,
    MetricUnit,
    MissingDataPolicy,
)
from .observation_pair_v2 import InterventionV2, ObservationRecordV2
from .observation_v2 import MetricMeasurement, ObservationWindowV2
from .response import (
    FeatureDelta,
    NormalizedFeature,
    NormalizedResponse,
    ObservationRecord,
    Probe,
    ResponseDelta,
)
from .v2_common import (
    OBSERVATION_V2_SCHEMA_VERSION,
    OBSERVATION_WINDOW_V2_SCHEMA_VERSION,
    V2_CONTRACT_VERSION,
    CaptureMethodReference,
    RegistryReference,
    SourceArtifactV2,
    V2ContextSnapshot,
)
from .v2_support import (
    MetricSupport,
    SourceSupport,
    StageTiming,
    WindowClock,
    WindowValidityV2,
)

__all__ += [
    "FINGERPRINT_V2_SCHEMA_VERSION",
    "FingerprintV2",
    "MATCH_RESULT_V2_SCHEMA_VERSION",
    "MatchResultV2",
    "CandidateComparisonV2",
    "AnalyticalFeatureEvidenceV2",
    "RankedCandidateV2",
    "RepositoryReferenceV2",
    "FEATURE_POLICY_SCHEMA_VERSION",
    "ANALYTICAL_RESPONSE_V2_SCHEMA_VERSION",
    "FeaturePolicyV1",
    "FeaturePolicyParameterV1",
    "AnalyticalDecisionPolicyV1",
    "AnalyticalResponseV2",
    "FeatureResponseV2",
    "WindowFeatureEvidenceV2",
    "V2_CONTRACT_VERSION",
    "OBSERVATION_V2_SCHEMA_VERSION",
    "OBSERVATION_WINDOW_V2_SCHEMA_VERSION",
    "ObservationWindowV2",
    "ObservationRecordV2",
    "InterventionV2",
    "MetricMeasurement",
    "V2ContextSnapshot",
    "RegistryReference",
    "CaptureMethodReference",
    "SourceArtifactV2",
    "SourceSupport",
    "MetricSupport",
    "StageTiming",
    "WindowClock",
    "WindowValidityV2",
]
