"""Read-only exact-byte and SHA-256 reproduction of N2 software fixtures."""

import hashlib
import json
import sys

from .fixture_cases import DEFAULT_FIXTURE_DIRECTORY, fixture_drift, rendered_fixture_files

# Reviewed software snapshot pins, independently retained from generated bytes.
EXPECTED_SHA256 = {
    "adopted-browser-v1.json": "50fd2ff8cb013a1d52564b5a21bbe210a25e810e0e55e036da5ca25c15911b81",
    "adopted-engine-v2.json": "f92e1fe241200609a8133be233053a79c7bbb3dca179ffd6ab3e1bbba09ab179",
    "synthetic-pair.json": "de35f8b1ea3c19b372079134988186ad0140778f33d5764ec03f675e7414c82e",
}


def check_reproduction() -> dict:
    drift = fixture_drift(DEFAULT_FIXTURE_DIRECTORY)
    if drift:
        raise ValueError(
            "N2 observation fixture drift: "
            + ", ".join(f"{path.name} ({state})" for path, state in sorted(drift.items()))
        )
    hashes = {
        path.name: hashlib.sha256(content).hexdigest()
        for path, content in rendered_fixture_files().items()
    }
    if hashes != EXPECTED_SHA256:
        raise ValueError("N2 observation fixture release pin mismatch")
    return {"status": "current", "contractVersion": "2.0.0", "fixtureSha256": hashes}


def main() -> int:
    try:
        result = check_reproduction()
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
